export enum ACTIONS_TYPES {
    ADD_PLACE = "ADD_PLACE",
    REMOVE_PLACE = "REMOVE_PLACE",
    ADD_TRANSITION = "ADD_TRANSITION",
    REMOVE_TRANSITION = "REMOVE_TRANSITION",
    ADD_INPUT = "ADD_INPUT",
    ADD_OUTPUT = "ADD_OUTPUT",
    REMOVE_INPUT = "REMOVE_INPUT",
    REMOVE_OUTPUT = "REMOVE_OUTPUT",
    RESET = "RESET",
}